management/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import include, path
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/',include('vehicles.urls')),
    path('',include('vehicles.urls')),
    path('', RedirectView.as_view(url='/login/')),

]

vehicles/urls.py
from django.urls import path
 
from .views import FuelDisbursementCreate, FuelDisbursementDetail, FuelDisbursementList, LocationAPIView, MaintenanceClose,\
    MaintenanceCreate, MileageRecordCreate, MileageRecordDetail, MileageRecordList, ProgrammeAPIView, ProvinceAPIView,\
    StatusAPIView, SubProgrammeAPIView, UpdateFuelDisbursement, UpdateMileageRecord, VehicleCreate,  VehicleDetail,\
    UpdateVehicle,MaintenanceList, MaintenanceDetail, UpdateMaintenance, UserProfileList, MaintenanceApiList,VehicleDetailsAPIView,\
    MileageRecordApiList,  check_vehicle_exists,vehicles_in_user_province,vehicles_list,VehicleMaintenanceCreate,FuelTypeAPIView,FuelReceivedCreate,\
    FuelReceivedList,MonthlyAllocationAPIView
   
from . import views


urlpatterns = [
    
    path('vehicle-create/', VehicleCreate.as_view(), name='vehicle-create'),
    path('vehicle-maintenance-create/', VehicleMaintenanceCreate.as_view(), name='vehicle-maintenance-create'),
    path('vehicle-detail/<int:pk>/', VehicleDetail.as_view(), name='vehicle-detail'),
    path('update-vehicle/<int:pk>/', UpdateVehicle.as_view(), name='update-vehicle'),
    path('check-number-plate/', check_vehicle_exists, name='check-number-plate'),
    path('vehicles-in-my-province/', vehicles_in_user_province, name='vehicles-in-my-province'),
    path('vehicles/', vehicles_list,name='vehicles'),
    
    #Maintenance API
    path('maintenance/', MaintenanceList.as_view(), name='maintenance'),
    path('maintenance-create/', MaintenanceCreate.as_view(), name='maintenance-create'),
    path('maintenance-detail/<int:pk>/', MaintenanceDetail.as_view(), name='maintenance-detail'),
    path('maintenance-update/<int:pk>/', UpdateMaintenance.as_view(), name='maintenance-update'),
    path('maintenance-close/<int:pk>/', MaintenanceClose.as_view(), name='maintenance-close'),  
    
    #Mileage API
    path('mileage/', MileageRecordList.as_view(), name='mileage'),
    path('mileage-create/', MileageRecordCreate.as_view(), name='mileage-create'),
    path('mileage-detail/<int:pk>/', MileageRecordDetail.as_view(), name='mileage-detail'),
    path('mileage-update/<int:pk>/', UpdateMileageRecord.as_view(), name='mileage-update'),
    
    #Fuel Disbursememt API
    path('fuel-disbursements/', FuelDisbursementList.as_view(), name='fuel-disbursement'),
    path('fuel-disbursement-create/', FuelDisbursementCreate.as_view(), name='fuel-disbursement-create'),
    path('fuel-disbursement-detail/<int:pk>/', FuelDisbursementDetail.as_view(), name='fuel-disbursement-detail'),
    path('fuel-disbursement-update/<int:pk>/', UpdateFuelDisbursement.as_view(), name='fuel-disbursement-update'),
    path('fuel-received-create/', FuelReceivedCreate.as_view(), name='fuel-received-create'),
    path('fuel-received-list/', FuelReceivedList.as_view(), name='fuel-received-list'),        
    #Dropdowns
    path('provinces/', ProvinceAPIView.as_view(), name='provinces'),
    path('locations/', LocationAPIView.as_view(), name='locations'),
    path('statuses/', StatusAPIView.as_view(), name='status'),
    path('fueltype/', FuelTypeAPIView.as_view(), name='fueltype'),
    path('monthly-allocation/', MonthlyAllocationAPIView.as_view(), name='monthly-allocation'),
    
    path('vehicle-user-list/', UserProfileList.as_view(), name="vehicle-user-list"), 
    
    path('sub-programmes/', SubProgrammeAPIView.as_view(), name='sub-programmes'),
    path('programmes/', ProgrammeAPIView.as_view(), name='programmes'),
    
    
    #Frontend
    path('dashboard/', views.index ,name='index'),
    path('vehicle-list/', views.vehicle_list, name='vehicle-list'),
    path('maintenance-list/', views.maintenance_list, name='maintenance-list'),
    path('mileage-list/', views.mileage_list, name='mileage-list'),
    path('fuel-disbursed/', views.fuel_disbursed, name='fuel-disbursed'),
    path('fuel-received/',views.fuel_received, name='fuel-received'),
    path('fuel-allocation/',views.fuel_allocation, name='fuel-allocation'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.user_logout_view, name='logout'), 
    
    path('vehicle-details/<int:vehicle_id>/', VehicleDetailsAPIView.as_view(), name='vehicle-details-api'),
    path('vehicles/<int:vehicle_id>/maintenance/', MaintenanceApiList.as_view(), name='vehicle-maintenance'),
    path('vehicles/<int:vehicle_id>/mileage/', MileageRecordApiList.as_view(), name='vehicle-mileage')
]

vehicles/models.py
from django.db import models
from django.contrib.auth.models import User

class Province(models.Model):
    province_name = models.CharField(max_length=100)

    def __str__(self):
        return self.province_name
    
class Location(models.Model):
    province = models.ForeignKey(Province,   on_delete=models.CASCADE)
    location_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.location_name
    
class Status(models.Model):
    status_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.status_name
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    province = models.ForeignKey(Province, on_delete=models.SET_NULL, null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)
    
class SubProgramme(models.Model):
    subProgramme_name = models.CharField(max_length=100)
    
class Programme(models.Model):
    subProgramme = models.ForeignKey(SubProgramme, on_delete=models.CASCADE)
    programme_name = models.CharField(max_length = 1000)

class FuelType(models.Model):
    fuel_type_name = models.CharField(max_length = 20)
    
class Vehicle(models.Model):
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    fueltype = models.ForeignKey(FuelType, on_delete=models.CASCADE)
    number_plate = models.CharField(max_length=20, unique=True)
    vehicle_type = models.CharField(max_length=100)
    engine_number = models.CharField(max_length=100)
    classis_number = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.number_plate} - {self.status}"

class Maintenance(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    status_at_service = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True, blank=True, related_name="maintenance_status")
    last_service_mileage = models.IntegerField()
    is_serviced = models.BooleanField(default=False)
    before_next_service_mileage = models.IntegerField()
    next_service_mileage = models.IntegerField()
    next_service_date = models.DateField(null=True)
    service_date = models.DateField(auto_now_add=True, null=True)
    service_type = models.CharField(max_length=500, null=True)
    service_provided= models.CharField(max_length=1000, null=True)
    service_provider= models.CharField(max_length=1000, null=True)
    remarks= models.CharField(max_length=1000, null=True)
    cost_incurred = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Maintenance for {self.vehicle.number_plate}"

class MileageRecord(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='mileage_records')
    mileage_reading = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Mileage record for {self.vehicle.number_plate}"
    
class FuelReceipt(models.Model):
    fueltype = models.ForeignKey(FuelType, on_delete=models.CASCADE)
    quantity_received = models.DecimalField(max_digits=10, decimal_places=2)  # In litres
    remaining_litres = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    received_date = models.DateField(auto_now_add=True)
    monthly = models.CharField(max_length=200,null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    is_used = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.fuel_type.type_name} - {self.quantity_received} litres received"

class FuelAllocation(models.Model):
    subProgramme = models.ForeignKey(SubProgramme, on_delete=models.CASCADE)
    fuel_receipt = models.ForeignKey(FuelReceipt, related_name='allocations', on_delete=models.CASCADE)
    allocated_litres = models.DecimalField(max_digits=10, decimal_places=2)
    remaining_litres = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    allocation_date = models.DateField(auto_now_add=True)
    
class FuelDisbursement(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    subProgramme= models.ForeignKey(SubProgramme, on_delete=models.CASCADE,null=True)
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE,null=True)
    driver = models.ForeignKey(UserProfile, on_delete=models.CASCADE,null=True)
    purpose = models.CharField(max_length=1000)
    amount_of_fuel_disbursed = models.DecimalField(max_digits=15, decimal_places=2)
    coupon_serial_number = models.CharField(max_length=50)
    issuer_name = models.CharField(max_length=100)
    transaction_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Fuel disbursement for {self.vehicle.number_plate}"

vehicles/views/mileage.py
#for frontend
from datetime import timezone
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required, permission_required
from rest_framework import status,permissions
import requests

#rest framework
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated

from ..models import  MileageRecord, UserProfile
from ..serializers import  MileageRecordSerializer

#Mileage API
""" class MileageRecordList(generics.ListAPIView):
    
    serializer_class = MileageRecordSerializer
    
    def get_queryset(self):
        # Get the queryset of Maintenance objects ordered by the created_at field in descending order
        queryset = MileageRecord.objects.order_by('-created_at')
        return queryset
     """

class MileageRecordList(generics.ListAPIView):
    serializer_class = MileageRecordSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user

        # Check if the user is a superuser and has a UserProfile
        if user.is_superuser:
            try:
                user_profile = UserProfile.objects.get(user=user)
                # For superusers with a province, return all MileageRecord instances in their province
                if user_profile.province:
                    return MileageRecord.objects.filter(vehicle__province=user_profile.province).order_by('-created_at')
                # If the superuser has no associated province, return all records
                return MileageRecord.objects.all().order_by('-created_at')
            except UserProfile.DoesNotExist:
                # If the superuser does not have a UserProfile, return all records
                return MileageRecord.objects.all().order_by('-created_at')

        # For regular users, filter MileageRecord instances based on the user's profile
        try:
            user_profile = UserProfile.objects.get(user=user)
            return MileageRecord.objects.filter(user_profile=user_profile).order_by('-created_at')
        except UserProfile.DoesNotExist:
            # If the regular user does not have a profile, return an empty queryset
            return MileageRecord.objects.none()
    
class MileageRecordCreate(APIView):
    
    permission_classes = [permissions.IsAuthenticated]
    
    def post(self, request, *args, **kwargs):
        serializer = MileageRecordSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            user_profile, created = UserProfile.objects.get_or_create(user=self.request.user)
            serializer.save(user_profile=user_profile)
            #serializer.save()
            return Response({"message": "Maintenance record created successfully"}, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def handle_exception(self, exc):
        # Check if the exception is a ValidationError with non_field_errors
        if hasattr(exc, 'get_full_details'):
            error_detail = exc.get_full_details()
            if 'non_field_errors' in error_detail:
                # Extract the non-field error message
                custom_error_message = error_detail['non_field_errors'][0]['message']
                # Return a custom response format
                return Response({"Error": custom_error_message}, status=status.HTTP_400_BAD_REQUEST)

        # Fallback to the default exception handling for other types of exceptions
        return super().handle_exception(exc)

class MileageRecordDetail(APIView):
    def get(self, request, pk):
        try:
            mileage_record = MileageRecord.objects.get(id=pk)
            serializer = MileageRecordSerializer(mileage_record)
            return Response(serializer.data)
        except MileageRecord.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

class UpdateMileageRecord(APIView):
    def get_object(self, pk):
        try:
            return MileageRecord.objects.get(id=pk)
        except MileageRecord.DoesNotExist:
            raise status.HTTP_404_NOT_FOUND

    def get(self, request, pk):
        mileage_detail_view = MileageRecordDetail()
        return mileage_detail_view.get(request, pk)

    def put(self, request, pk):
        mileage_record = self.get_object(pk)
        serializer = MileageRecordSerializer(mileage_record, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    
class MileageRecordApiList(APIView):
    """
    List all mileage records for a vehicle.
    """
    def get(self, request, vehicle_id):
        mileage_records = MileageRecord.objects.filter(vehicle_id=vehicle_id).order_by('-created_at')
        serializer = MileageRecordSerializer(mileage_records, many=True)
        return Response(serializer.data)

templates/pages/mileage/addMileage.html
<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="addMileageModal" tabindex="-1" role="dialog" aria-labelledby="addMileageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addMileageModalLabel">Add Vehicle Mileage</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addMileageForm" autocomplete="off" style="font-size:15px">
                   <div class="row">
                        <div class="mb-3 col-md-3">
                            <div class="form-group">
                                <label for="vehicle">Vehicle</label>
                                <select class="form-control" id="vehicle" name="vehicle" required>
                                    <option value="" selected disabled>Select Vehicle</option>
                                </select>
                            </div>
                        </div>

                        <div class="mb-3 col-md-6">
                            <div class="form-group">
                                <label for="mileage_reading">Mileage Reading</label>
                                <input type="number" class="form-control" id="mileage_reading" name="mileage_reading" placeholder="Enter Mileage Reading" required>
                            </div>
                        </div>
        
                   </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-primary btn-sm" id="submitMileageBtn">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>




    

templates/pages/mileage/editMileage.html
<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="editMileageModal" tabindex="-1" role="dialog" aria-labelledby="editMileageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="editMileageModalLabel"> Update Mileage Record</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="editMileageForm" autocomplete="off" style="font-size: 15px">
                  <div class="row">
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label for="vehicle">Vehicle</label>
                            <select class="form-control" id="vehicle" name="vehicle" required>
                                <option value="" selected disabled>Select Vehicle</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label for="vehicle_user ">Vehicle User</label>
                            <input type="text" class="form-control"  id="vehicle_user" name="vehicle_user" value="{{ mileage.vehicle_user }}"  required>
                        </div>
                    </div>
                
                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label for="mileage_date">Date of Mileage</label>
                            <input type="date" class="form-control" id="mileage_date" name="mileage_date" value="{{ mileage.mileage_date }}" required>
                        </div>
                    </div>

                    <div class="mb-3 col-md-6">
                        <div class="form-group">
                            <label for="mileage_reading">Mileage Reading</label>
                            <input type="number" class="form-control" id="mileage_reading" name="mileage_reading" value="{{ mileage.mileage_reading }}" required>
                        </div>
                    </div>
    
                  </div>
                  
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" id="submitMaintenanceBtn">Update</button>
                  </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="toastContainer" aria-live="polite" aria-atomic="true" style="position: fixed; top: 16px; right: 16px; z-index: 9999;"></div>
    <!-- Popup -->
    <div class="modal fade" id="numberPlateExistsModal" tabindex="-1" role="dialog" aria-labelledby="numberPlateExistsModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="numberPlateExistsModalLabel">Number Plate Already Exists</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>The number plate you entered already exists. Please enter a different number plate.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>


    

templates/pages/mileage/mileage.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}| Mileage {% endblock title %}
{% block extrastyle %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">

{% endblock extrastyle %}
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Mileage</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div id="successMessage" class="alert alert-success alert-dismissible fade show" role="alert" style="display: none;">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
        </div>
        
        <div id="errorMessage" class="alert alert-danger alert-dismissible fade show" role="alert" style="display: none;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h1 class="card-title">Mileage of Vehicles</h1>
                <div class="d-flex justify-content-end">
                  {% if perms.vehicles.add_mileagerecord  %}
                  <a class="btn btn-success btn-sm" href="#" data-toggle="modal" data-target="#addMileageModal"><i class="fas fa-plus-circle"></i> Add Mileage </a>
                  {% endif %}
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="dataTable" class="table table-striped dt-responsive nowrap table-sm" style="font-size:15px">
                  <thead style="background-color: lightblue;">
                    <tr>
                      <th>No.</th>
                      <th>Vehicle</th>
                      <th>Driver</th>
                      <th>Mileage Date</th>
                      <th>Mileage Reading</th>
                      <th>Province</th>
                      <th>Location</th>
                      {% if perms.vehicles.mileage_actions  %}
                      <th>Actions</th>
                      {% endif %}
                    </tr>
                  </thead>
                  <tbody>
                    {% for mileage in mileage_records %}
                        <tr>
                          <td>{{ forloop.counter }}</td>
                          <td>{{ mileage.number_plate }}</td>
                          <td>{{ mileage.user_profile.user.first_name }} {{ mileage.user_profile.user.last_name }}</td>
                          <td>{{ mileage.created_at }}</td>
                          <td>{{ mileage.mileage_reading }}</td>
                          <td>{{ mileage.user_profile.province.province_name }}</td>
                          <td>{{ mileage.user_profile.location.location_name }}</td>
                          {% if perms.vehicles.mileage_actions  %}
                          <td class="project-actions">
                            {% if perms.vehicles.view_mileagerecord  %}
                            <a class="btn btn-outline-info btn-sm" href="#" style="padding: 0px 1px; font-size: 13px; color: #322929;">
                              <i class="fas fa-eye"></i> View
                            </a>
                            {% endif %}
                            {% if perms.vehicles.change_mileagerecord %}
                            <a class="btn btn-outline-info btn-sm edit-mileage-link" href="#" data-toggle="modal" data-target="#editMileageModal" data-mileage-id="{{ mileage.id }}" style="padding: 0px 1px; font-size: 13px; color: #322929;">
                              <i class="fas fa-pencil-alt"></i> Edit
                            </a>
                            {% endif %}
                          </td>
                          {% endif %}
                        </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  {% include 'pages/mileage/addMileage.html' %}
  {% include 'pages/mileage/editMileage.html' %}  
{% endblock content %}

{% block extra_scripts %}
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- Page specific script -->
{% include 'pages/mileage/scripts.html' %}

{% endblock extra_scripts %}