management/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import include, path
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/',include('vehicles.urls')),
    path('',include('vehicles.urls')),
    path('', RedirectView.as_view(url='/login/')),

]

vehicles/urls.py
from django.urls import path
 
from .views import FuelDisbursementCreate, FuelDisbursementDetail, FuelDisbursementList, LocationAPIView, MaintenanceClose,\
    MaintenanceCreate, MileageRecordCreate, MileageRecordDetail, MileageRecordList, ProgrammeAPIView, ProvinceAPIView,\
    StatusAPIView, SubProgrammeAPIView, UpdateFuelDisbursement, UpdateMileageRecord, VehicleCreate,  VehicleDetail,\
    UpdateVehicle,MaintenanceList, MaintenanceDetail, UpdateMaintenance, UserProfileList, MaintenanceApiList,VehicleDetailsAPIView,\
    MileageRecordApiList,  check_vehicle_exists,vehicles_in_user_province,vehicles_list,VehicleMaintenanceCreate,FuelTypeAPIView,FuelReceivedCreate,\
    FuelReceivedList,MonthlyAllocationAPIView
   
from . import views


urlpatterns = [
    
    path('vehicle-create/', VehicleCreate.as_view(), name='vehicle-create'),
    path('vehicle-maintenance-create/', VehicleMaintenanceCreate.as_view(), name='vehicle-maintenance-create'),
    path('vehicle-detail/<int:pk>/', VehicleDetail.as_view(), name='vehicle-detail'),
    path('update-vehicle/<int:pk>/', UpdateVehicle.as_view(), name='update-vehicle'),
    path('check-number-plate/', check_vehicle_exists, name='check-number-plate'),
    path('vehicles-in-my-province/', vehicles_in_user_province, name='vehicles-in-my-province'),
    path('vehicles/', vehicles_list,name='vehicles'),
    
    #Maintenance API
    path('maintenance/', MaintenanceList.as_view(), name='maintenance'),
    path('maintenance-create/', MaintenanceCreate.as_view(), name='maintenance-create'),
    path('maintenance-detail/<int:pk>/', MaintenanceDetail.as_view(), name='maintenance-detail'),
    path('maintenance-update/<int:pk>/', UpdateMaintenance.as_view(), name='maintenance-update'),
    path('maintenance-close/<int:pk>/', MaintenanceClose.as_view(), name='maintenance-close'),  
    
    #Mileage API
    path('mileage/', MileageRecordList.as_view(), name='mileage'),
    path('mileage-create/', MileageRecordCreate.as_view(), name='mileage-create'),
    path('mileage-detail/<int:pk>/', MileageRecordDetail.as_view(), name='mileage-detail'),
    path('mileage-update/<int:pk>/', UpdateMileageRecord.as_view(), name='mileage-update'),
    
    #Fuel Disbursememt API
    path('fuel-disbursements/', FuelDisbursementList.as_view(), name='fuel-disbursement'),
    path('fuel-disbursement-create/', FuelDisbursementCreate.as_view(), name='fuel-disbursement-create'),
    path('fuel-disbursement-detail/<int:pk>/', FuelDisbursementDetail.as_view(), name='fuel-disbursement-detail'),
    path('fuel-disbursement-update/<int:pk>/', UpdateFuelDisbursement.as_view(), name='fuel-disbursement-update'),
    path('fuel-received-create/', FuelReceivedCreate.as_view(), name='fuel-received-create'),
    path('fuel-received-list/', FuelReceivedList.as_view(), name='fuel-received-list'),        
    #Dropdowns
    path('provinces/', ProvinceAPIView.as_view(), name='provinces'),
    path('locations/', LocationAPIView.as_view(), name='locations'),
    path('statuses/', StatusAPIView.as_view(), name='status'),
    path('fueltype/', FuelTypeAPIView.as_view(), name='fueltype'),
    path('monthly-allocation/', MonthlyAllocationAPIView.as_view(), name='monthly-allocation'),
    
    path('vehicle-user-list/', UserProfileList.as_view(), name="vehicle-user-list"), 
    
    path('sub-programmes/', SubProgrammeAPIView.as_view(), name='sub-programmes'),
    path('programmes/', ProgrammeAPIView.as_view(), name='programmes'),
    
    
    #Frontend
    path('dashboard/', views.index ,name='index'),
    path('vehicle-list/', views.vehicle_list, name='vehicle-list'),
    path('maintenance-list/', views.maintenance_list, name='maintenance-list'),
    path('mileage-list/', views.mileage_list, name='mileage-list'),
    path('fuel-disbursed/', views.fuel_disbursed, name='fuel-disbursed'),
    path('fuel-received/',views.fuel_received, name='fuel-received'),
    path('fuel-allocation/',views.fuel_allocation, name='fuel-allocation'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.user_logout_view, name='logout'), 
    
    path('vehicle-details/<int:vehicle_id>/', VehicleDetailsAPIView.as_view(), name='vehicle-details-api'),
    path('vehicles/<int:vehicle_id>/maintenance/', MaintenanceApiList.as_view(), name='vehicle-maintenance'),
    path('vehicles/<int:vehicle_id>/mileage/', MileageRecordApiList.as_view(), name='vehicle-mileage')
]

vehicles/models.py
from django.db import models
from django.contrib.auth.models import User

class Province(models.Model):
    province_name = models.CharField(max_length=100)

    def __str__(self):
        return self.province_name
    
class Location(models.Model):
    province = models.ForeignKey(Province,   on_delete=models.CASCADE)
    location_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.location_name
    
class Status(models.Model):
    status_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.status_name
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    province = models.ForeignKey(Province, on_delete=models.SET_NULL, null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)
    
class SubProgramme(models.Model):
    subProgramme_name = models.CharField(max_length=100)
    
class Programme(models.Model):
    subProgramme = models.ForeignKey(SubProgramme, on_delete=models.CASCADE)
    programme_name = models.CharField(max_length = 1000)

class FuelType(models.Model):
    fuel_type_name = models.CharField(max_length = 20)
    
class Vehicle(models.Model):
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    fueltype = models.ForeignKey(FuelType, on_delete=models.CASCADE)
    number_plate = models.CharField(max_length=20, unique=True)
    vehicle_type = models.CharField(max_length=100)
    engine_number = models.CharField(max_length=100)
    classis_number = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.number_plate} - {self.status}"

class Maintenance(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    status_at_service = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True, blank=True, related_name="maintenance_status")
    last_service_mileage = models.IntegerField()
    is_serviced = models.BooleanField(default=False)
    before_next_service_mileage = models.IntegerField()
    next_service_mileage = models.IntegerField()
    next_service_date = models.DateField(null=True)
    service_date = models.DateField(auto_now_add=True, null=True)
    service_type = models.CharField(max_length=500, null=True)
    service_provided= models.CharField(max_length=1000, null=True)
    service_provider= models.CharField(max_length=1000, null=True)
    remarks= models.CharField(max_length=1000, null=True)
    cost_incurred = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Maintenance for {self.vehicle.number_plate}"

class MileageRecord(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='mileage_records')
    mileage_reading = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Mileage record for {self.vehicle.number_plate}"
    
class FuelReceipt(models.Model):
    fueltype = models.ForeignKey(FuelType, on_delete=models.CASCADE)
    quantity_received = models.DecimalField(max_digits=10, decimal_places=2)  # In litres
    remaining_litres = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    received_date = models.DateField(auto_now_add=True)
    monthly = models.CharField(max_length=200,null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    is_used = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.fuel_type.type_name} - {self.quantity_received} litres received"

class FuelAllocation(models.Model):
    subProgramme = models.ForeignKey(SubProgramme, on_delete=models.CASCADE)
    fuel_receipt = models.ForeignKey(FuelReceipt, related_name='allocations', on_delete=models.CASCADE)
    allocated_litres = models.DecimalField(max_digits=10, decimal_places=2)
    remaining_litres = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    allocation_date = models.DateField(auto_now_add=True)
    
class FuelDisbursement(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    subProgramme= models.ForeignKey(SubProgramme, on_delete=models.CASCADE,null=True)
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE,null=True)
    driver = models.ForeignKey(UserProfile, on_delete=models.CASCADE,null=True)
    purpose = models.CharField(max_length=1000)
    amount_of_fuel_disbursed = models.DecimalField(max_digits=15, decimal_places=2)
    coupon_serial_number = models.CharField(max_length=50)
    issuer_name = models.CharField(max_length=100)
    transaction_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Fuel disbursement for {self.vehicle.number_plate}"

vehicles/forms.py
from django import forms
from django.contrib.auth.forms import  AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username'
    }))
    password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password'
    }))

vehicles/views/frontend.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required, permission_required
import requests
from django.conf import settings
#rest framework
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView

from ..models import FuelDisbursement, Location, Maintenance, MileageRecord, Programme, Province, Status, SubProgramme, Vehicle, UserProfile


#Frontend Urls
@login_required(login_url="/login")
def index(request):
 
  return render(request, 'pages/dashboard/index.html')

@login_required(login_url="/login")
def vehicle_list(request):
    # Assuming session-based authentication with your Django backend
    session_id = request.COOKIES.get('sessionid')

    # Make a GET request to fetch a list of vehicles, including the session cookie for authentication
    response = requests.get(
        f'{settings.API_BASE_URL}/api/v1/vehicles-in-my-province/',
        cookies={'sessionid': session_id} if session_id else {}
    )

    if response.status_code == 200:
        vehicles = response.json()  # Extract JSON data from the response
        return render(request, 'pages/vehicle/vehicle.html', {'vehicles': vehicles})
    else:
        # Handle the case where the request was not successful
        return render(request, 'error.html', {'message': 'Failed to fetch vehicles from your province'})
    

@login_required(login_url="/login")
def maintenance_list(request):
    # Assuming session-based authentication with your Django backend
    session_id = request.COOKIES.get('sessionid')

    # Make a GET request to fetch a list of vehicles, including the session cookie for authentication
    response = requests.get(
        f'{settings.API_BASE_URL}/api/v1/maintenance/',
        cookies={'sessionid': session_id} if session_id else {}
    )

    if response.status_code == 200:
        maintenance_list = response.json()  # Extract JSON data from the response
        return render(request, 'pages/maintenance/maintenance.html', {'maintenance_list': maintenance_list})
    else:
        # Handle the case where the request was not successful
        return render(request, 'error.html', {'message': 'Failed to fetch Maintenance list'})

@login_required(login_url="/login")
def mileage_list(request):
    # Assuming session-based authentication with your Django backend
    session_id = request.COOKIES.get('sessionid')

    # Make a GET request to fetch a list of vehicles, including the session cookie for authentication
    response = requests.get(
        f'{settings.API_BASE_URL}/api/v1/mileage/',
        cookies={'sessionid': session_id} if session_id else {}
    )

    if response.status_code == 200:
        mileage_records = response.json()  # Extract JSON data from the response
        return render(request, 'pages/mileage/mileage.html', {'mileage_records': mileage_records})
    else:
        # Handle the case where the request was not successful
        return render(request, 'error.html', {'message': 'Failed to fetch Mileage Vehicles'})

@login_required(login_url="/login")
def fuel_disbursed(request):
    # Make a GET request to fetch a list of vehicles
    response = requests.get(f'{settings.API_BASE_URL}/api/v1/fuel-disbursements/')
    
    # Check if the request was successful
    if response.status_code == 200:
        fuel_disbursements= response.json()  # Extract JSON data from the response
        return render(request, 'pages/fuel/fuel_disbursed.html', {'fuel_disbursements': fuel_disbursements})
    else:
        # Handle the case where the request was not successful
        return render(request, 'error.html', {'message': 'Failed to fetch vehicles'})

@login_required(login_url="/login")  
def fuel_received(request):
    
    response = requests.get(f'{settings.API_BASE_URL}/api/v1/fuel-received-list/')
    
    if response.status_code == 200:
        received= response.json()  # Extract JSON data from the response
        return render(request, 'pages/fuel/fuel_received.html', {'received': received})
    else:
        # Handle the case where the request was not successful
        return render(request, 'error.html', {'message': 'Failed to fetch vehicles'})
    
@login_required(login_url="/login")  
def fuel_allocation(request):
    
    response = requests.get(f'{settings.API_BASE_URL}/api/v1/fuel-received-list/')
    
    if response.status_code == 200:
        allocations= response.json()  # Extract JSON data from the response
        return render(request, 'pages/fuel/fuel_allocation.html', {'allocations': allocations})
    else:
        # Handle the case where the request was not successful
        return render(request, 'error.html', {'message': 'Failed to fetch vehicles'})
    
  

vehicles/views/users.py
from django.shortcuts import redirect
from ..forms import LoginForm
from django.contrib.auth import logout
from django.contrib.auth import views as auth_views


class UserLoginView(auth_views.LoginView):
  template_name = 'accounts/login.html'
  form_class = LoginForm
  success_url = '/dashboard'

def user_logout_view(request):
  logout(request)
  return redirect('/login')
  

templates/pages/vehicle/editVehicle.html
<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="editVehicleModal" tabindex="-1" role="dialog" aria-labelledby="editVehicleModalLabel" aria-hidden="true" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="editVehicleModalLabel">Update Vehicle Record</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="editVehicleForm" style="font-size:15px">
                    {% csrf_token %}
                    <input type="hidden" id="vehicle_id" name="vehicle_id">
                    <div class="row g-2">
                        <div class="mb-3 col-md-6">
                            <div class="form-group">
                                <label for="number_plate">Number Plate</label>
                                <input type="text" class="form-control" id="number_plate" name="number_plate" value="{{ vehicle.number_plate }}">
                            </div>
                        </div>
                        <div class="mb-3 col-md-6">
                            <div class="form-group">
                                <label for="vehicle_type">Vehicle Type</label>
                                <select class="form-control" id="vehicle_type" name="vehicle_type" required>
                                    <option selected="selected" disabled="disabled">Select Vehicle Type</option>
                                    <option value="Land Cruiser VX" {% if vehicle.vehicle_type == "Land Cruiser VX" %} selected {% endif %}>Land Cruiser VX</option>
                                    <option value="Isuzu D/cab" {% if vehicle.vehicle_type == "Isuzu D/cab" %} selected {% endif %}>Isuzu D/cab</option>
                                    <option value="Isuzu S/cab" {% if vehicle.vehicle_type == "Isuzu S/cab" %} selected {% endif %}>Isuzu S/cab</option>
                                    <option value="FOTON" {% if vehicle.vehicle_type == "FOTON" %} selected {% endif %}>FOTON</option>
                                    <option value="JMC S/cab" {% if vehicle.vehicle_type == "JMC S/cab" %} selected {% endif %}>JMC S/cab</option>
                                    <option value="Mazda S/cab" {% if vehicle.vehicle_type == "Mazda S/cab" %} selected {% endif %}>Mazda S/cab</option>
                                    <option value="Mazda Eagle" {% if vehicle.vehicle_type == "Mazda Eagle" %} selected {% endif %}>Mazda Eagle</option>
                                    <option value="Mazda BT50" {% if vehicle.vehicle_type == "Mazda BT50" %} selected {% endif %}>Mazda BT50</option>
                                    <option value="Mazda T35 Bus" {% if vehicle.vehicle_type == "Mazda T35 Bus" %} selected {% endif %}>Mazda T35 Bus</option>
                                    <option value="Mazda BT50/KINGCAB" {% if vehicle.vehicle_type == "Mazda BT50/KINGCAB" %} selected {% endif %}>Mazda BT50/KINGCAB</option>
                                    <option value="Mitsubishi S/Cab" {% if vehicle.vehicle_type == "Mitsubishi S/Cab" %} selected {% endif %}>Mitsubishi S/Cab</option>
                                    <option value="Mitsubishi L200" {% if vehicle.vehicle_type == "Mitsubishi L200" %} selected {% endif %}>Mitsubishi L200</option>
                                    <option value="Mitsubishi Lorry" {% if vehicle.vehicle_type == "Mitsubishi Lorry" %} selected {% endif %}>Mitsubishi Lorry</option>
                                    <option value="Toyota Coaster" {% if vehicle.vehicle_type == "Toyota Coaster" %} selected {% endif %}>Toyota Coaster</option>
                                    <option value="Toyota Prado" {% if vehicle.vehicle_type == "Toyota Prado" %} selected {% endif %}>Toyota Prado</option>
                                    <option value="Toyota Hilux" {% if vehicle.vehicle_type == "Toyota Hilux" %} selected {% endif %}>Toyota Hilux</option>
                                    <option value="Toyota Landcruiser" {% if vehicle.vehicle_type == "Toyota Landcruiser" %} selected {% endif %}>Toyota Landcruiser</option>
                                    <option value="Toyota Avensis" {% if vehicle.vehicle_type == "Toyota Avensis" %} selected {% endif %}>Toyota Avensis</option>
                                    <option value="Nissan NP300 D/CAB" {% if vehicle.vehicle_type == "Nissan NP300 D/CAB" %} selected {% endif %}>Nissan NP300 D/CAB</option>
                                    <option value="Nissan D/Cab" {% if vehicle.vehicle_type == "Nissan D/Cab" %} selected {% endif %}>Nissan D/Cab</option>
                                    <option value="Nissan H/Body" {% if vehicle.vehicle_type == "Nissan H/Body" %} selected {% endif %}>Nissan H/Body</option>
                                    <option value="Nissan" {% if vehicle.vehicle_type == "Nissan" %} selected {% endif %}>Nissan</option>
                                    <option value="Nissan Hardbody S/CAB" {% if vehicle.vehicle_type == "Nissan Hardbody S/CAB" %} selected {% endif %}>Nissan Hardbody S/CAB</option>
                                </select>
                                                              
                            </div>
                        </div>
                    </div>
                    <div class="row g-2">
                        <div class="mb-3 col-md-6">
                            <div class="form-group">
                                <label for="engine_number">Engine Number</label>
                                <input type="text" class="form-control" id="engine_number" name="engine_number" placeholder="Enter Engine Number" required>
                            </div>
                        </div>

                        <div class="mb-3 col-md-6">
                            <div class="form-group">
                                <label for="classis_number">Classis Number</label>
                                <input type="text" class="form-control" id="classis_number" name="classis_number" placeholder="Enter Classis Number" required>   
                            </div>
                        </div>
                    </div>

                    <div class="row g-2"> 
                        <div class="mb-3 col-md-3">
                            <div class="form-group">
                                <label for="province">Province</label>
                                    <select class="form-control select2" id="province-dropdown" name="province">
                                    </select>
                            </div>
                        </div>

                        <div class="mb-3 col-md-3">
                            <div class="form-group">
                                <label for="location">Location</label>
                                <select class="form-control select2" id="location-dropdown" name="location">
                                    <!-- Options will be populated dynamically -->
                                </select>                              
                            </div>
                        </div>

                        <div class="mb-3 col-md-6">
                            <div class="form-group">
                                <label for="status">Status</label>
                                <select class="form-control select2"  id="status" name="status" required>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/pages/vehicle/vehicle.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}| Vehicles {% endblock title %}
{% block extrastyle %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">

{% endblock extrastyle %}
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Vehicles</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div id="successMessage" class="alert alert-success alert-dismissible fade show" role="alert" style="display: none;">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
        </div>
        
        <div id="errorMessage" class="alert alert-danger alert-dismissible fade show" role="alert" style="display: none;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h1 class="card-title">Vehicles</h1>
                <div class="d-flex justify-content-end">
                  
                  {% if perms.vehicles.add_vehicle  %}
                  <a class="btn btn-success btn-sm" href="#" data-toggle="modal" data-target="#addVehicleModal"><i class="fas fa-plus-circle"></i> Add Vehicle </a>
                  {% endif %}
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="dataTable" class="table table-striped dt-responsive nowrap table-sm" style="font-size:15px">
                  <thead style="background-color: lightblue;">
                    <tr>
                      <th>No.</th>
                      <th>Vehicle Number</th>
                      <th>Vehicle Type</th>
                      <th>Province</th>
                      <th>Location</th>
                      <th>Fuel Type</th>
                      <th>Status</th>
                      {% if perms.vehicles.vehicle_actions  %}
                      <th>Actions</th>
                      {% endif %}
                    </tr>
                  </thead>
                  <tbody>
                      {% for vehicle in vehicles %}
                        <tr>
                          <td>{{ forloop.counter }}</td>
                          <td>{{ vehicle.number_plate }}</td>
                          <td>{{ vehicle.vehicle_type }}</td>
                          <td>{{ vehicle.province_name }}</td>
                          <td>{{ vehicle.location_name }}</td>
                          <td>{{ vehicle.fuel_type}}</td>
                          <td>
                            {% if vehicle.status_name == 'Serviced' %}
                                <span class="badge badge-success">{{ vehicle.status_name }}</span>
                            {% elif vehicle.status_name == 'Due' %}
                                <span class="badge badge-warning">{{ vehicle.status_name }}</span>
                            {% elif vehicle.status_name == 'Overdue' %}
                                <span class="badge badge-danger">{{ vehicle.status_name }}</span>
                            {% elif vehicle.status_name == 'Non Runner' %}
                                <span class="badge badge-secondary">{{ vehicle.status_name }}</span>
                            {% endif %}
                          </td>
                         
                           {% if perms.vehicles.vehicle_actions  %}
                          <td class="project-actions">
                            {% if perms.vehicles.view_vehicle  %}
                            <a class="btn btn-outline-info btn-sm view-details" href="#" data-toggle="modal" data-target="#viewVehicleModal" data-vehicle-id="{{ vehicle.id }}" style="padding: 0px 1px; font-size: 13px; color: #232121;">
                              <i class="fas fa-eye"></i> View
                            </a>
                            {% endif %}
                            {% if perms.vehicles.change_vehicle  %}
                            <a class="btn btn-outline-info btn-sm edit-vehicle-link" href="#" data-toggle="modal" data-target="#editVehicleModal" data-vehicle-id="{{ vehicle.id }}" style="padding: 0px 1px; font-size: 13px; color: #232121;">
                              <i class="fas fa-pencil-alt"></i> Edit
                            </a>
                            {% endif %}
                          </td>
                          {% endif %}
                        </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  {% include 'pages/vehicle/addVehicle.html' %}
  {% include 'pages/vehicle/editVehicle.html' %}
  {% include 'pages/vehicle/viewVehicle.html' %}
{% endblock content %}


{% block extra_scripts %}
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- Page specific script -->

{% include 'pages/vehicle/scripts.html' %}
  
{% endblock extra_scripts %}