management/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import include, path
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/',include('vehicles.urls')),
    path('',include('vehicles.urls')),
    path('', RedirectView.as_view(url='/login/')),

]

vehicles/urls.py
from django.urls import path
 
from .views import FuelDisbursementCreate, FuelDisbursementDetail, FuelDisbursementList, LocationAPIView, MaintenanceClose,\
    MaintenanceCreate, MileageRecordCreate, MileageRecordDetail, MileageRecordList, ProgrammeAPIView, ProvinceAPIView,\
    StatusAPIView, SubProgrammeAPIView, UpdateFuelDisbursement, UpdateMileageRecord, VehicleCreate,  VehicleDetail,\
    UpdateVehicle,MaintenanceList, MaintenanceDetail, UpdateMaintenance, UserProfileList, MaintenanceApiList,VehicleDetailsAPIView,\
    MileageRecordApiList,  check_vehicle_exists,vehicles_in_user_province,vehicles_list,VehicleMaintenanceCreate,FuelTypeAPIView,FuelReceivedCreate,\
    FuelReceivedList,MonthlyAllocationAPIView
   
from . import views


urlpatterns = [
    
    path('vehicle-create/', VehicleCreate.as_view(), name='vehicle-create'),
    path('vehicle-maintenance-create/', VehicleMaintenanceCreate.as_view(), name='vehicle-maintenance-create'),
    path('vehicle-detail/<int:pk>/', VehicleDetail.as_view(), name='vehicle-detail'),
    path('update-vehicle/<int:pk>/', UpdateVehicle.as_view(), name='update-vehicle'),
    path('check-number-plate/', check_vehicle_exists, name='check-number-plate'),
    path('vehicles-in-my-province/', vehicles_in_user_province, name='vehicles-in-my-province'),
    path('vehicles/', vehicles_list,name='vehicles'),
    
    #Maintenance API
    path('maintenance/', MaintenanceList.as_view(), name='maintenance'),
    path('maintenance-create/', MaintenanceCreate.as_view(), name='maintenance-create'),
    path('maintenance-detail/<int:pk>/', MaintenanceDetail.as_view(), name='maintenance-detail'),
    path('maintenance-update/<int:pk>/', UpdateMaintenance.as_view(), name='maintenance-update'),
    path('maintenance-close/<int:pk>/', MaintenanceClose.as_view(), name='maintenance-close'),  
    
    #Mileage API
    path('mileage/', MileageRecordList.as_view(), name='mileage'),
    path('mileage-create/', MileageRecordCreate.as_view(), name='mileage-create'),
    path('mileage-detail/<int:pk>/', MileageRecordDetail.as_view(), name='mileage-detail'),
    path('mileage-update/<int:pk>/', UpdateMileageRecord.as_view(), name='mileage-update'),
    
    #Fuel Disbursememt API
    path('fuel-disbursements/', FuelDisbursementList.as_view(), name='fuel-disbursement'),
    path('fuel-disbursement-create/', FuelDisbursementCreate.as_view(), name='fuel-disbursement-create'),
    path('fuel-disbursement-detail/<int:pk>/', FuelDisbursementDetail.as_view(), name='fuel-disbursement-detail'),
    path('fuel-disbursement-update/<int:pk>/', UpdateFuelDisbursement.as_view(), name='fuel-disbursement-update'),
    path('fuel-received-create/', FuelReceivedCreate.as_view(), name='fuel-received-create'),
    path('fuel-received-list/', FuelReceivedList.as_view(), name='fuel-received-list'),        
    #Dropdowns
    path('provinces/', ProvinceAPIView.as_view(), name='provinces'),
    path('locations/', LocationAPIView.as_view(), name='locations'),
    path('statuses/', StatusAPIView.as_view(), name='status'),
    path('fueltype/', FuelTypeAPIView.as_view(), name='fueltype'),
    path('monthly-allocation/', MonthlyAllocationAPIView.as_view(), name='monthly-allocation'),
    
    path('vehicle-user-list/', UserProfileList.as_view(), name="vehicle-user-list"), 
    
    path('sub-programmes/', SubProgrammeAPIView.as_view(), name='sub-programmes'),
    path('programmes/', ProgrammeAPIView.as_view(), name='programmes'),
    
    
    #Frontend
    path('dashboard/', views.index ,name='index'),
    path('vehicle-list/', views.vehicle_list, name='vehicle-list'),
    path('maintenance-list/', views.maintenance_list, name='maintenance-list'),
    path('mileage-list/', views.mileage_list, name='mileage-list'),
    path('fuel-disbursed/', views.fuel_disbursed, name='fuel-disbursed'),
    path('fuel-received/',views.fuel_received, name='fuel-received'),
    path('fuel-allocation/',views.fuel_allocation, name='fuel-allocation'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.user_logout_view, name='logout'), 
    
    path('vehicle-details/<int:vehicle_id>/', VehicleDetailsAPIView.as_view(), name='vehicle-details-api'),
    path('vehicles/<int:vehicle_id>/maintenance/', MaintenanceApiList.as_view(), name='vehicle-maintenance'),
    path('vehicles/<int:vehicle_id>/mileage/', MileageRecordApiList.as_view(), name='vehicle-mileage')
]

vehicles/models.py
from django.db import models
from django.contrib.auth.models import User

class Province(models.Model):
    province_name = models.CharField(max_length=100)

    def __str__(self):
        return self.province_name
    
class Location(models.Model):
    province = models.ForeignKey(Province,   on_delete=models.CASCADE)
    location_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.location_name
    
class Status(models.Model):
    status_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.status_name
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    province = models.ForeignKey(Province, on_delete=models.SET_NULL, null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)
    
class SubProgramme(models.Model):
    subProgramme_name = models.CharField(max_length=100)
    
class Programme(models.Model):
    subProgramme = models.ForeignKey(SubProgramme, on_delete=models.CASCADE)
    programme_name = models.CharField(max_length = 1000)

class FuelType(models.Model):
    fuel_type_name = models.CharField(max_length = 20)
    
class Vehicle(models.Model):
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    fueltype = models.ForeignKey(FuelType, on_delete=models.CASCADE)
    number_plate = models.CharField(max_length=20, unique=True)
    vehicle_type = models.CharField(max_length=100)
    engine_number = models.CharField(max_length=100)
    classis_number = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.number_plate} - {self.status}"

class Maintenance(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    status_at_service = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True, blank=True, related_name="maintenance_status")
    last_service_mileage = models.IntegerField()
    is_serviced = models.BooleanField(default=False)
    before_next_service_mileage = models.IntegerField()
    next_service_mileage = models.IntegerField()
    next_service_date = models.DateField(null=True)
    service_date = models.DateField(auto_now_add=True, null=True)
    service_type = models.CharField(max_length=500, null=True)
    service_provided= models.CharField(max_length=1000, null=True)
    service_provider= models.CharField(max_length=1000, null=True)
    remarks= models.CharField(max_length=1000, null=True)
    cost_incurred = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Maintenance for {self.vehicle.number_plate}"

class MileageRecord(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='mileage_records')
    mileage_reading = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Mileage record for {self.vehicle.number_plate}"
    
class FuelReceipt(models.Model):
    fueltype = models.ForeignKey(FuelType, on_delete=models.CASCADE)
    quantity_received = models.DecimalField(max_digits=10, decimal_places=2)  # In litres
    remaining_litres = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    received_date = models.DateField(auto_now_add=True)
    monthly = models.CharField(max_length=200,null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    is_used = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.fuel_type.type_name} - {self.quantity_received} litres received"

class FuelAllocation(models.Model):
    subProgramme = models.ForeignKey(SubProgramme, on_delete=models.CASCADE)
    fuel_receipt = models.ForeignKey(FuelReceipt, related_name='allocations', on_delete=models.CASCADE)
    allocated_litres = models.DecimalField(max_digits=10, decimal_places=2)
    remaining_litres = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    allocation_date = models.DateField(auto_now_add=True)
    
class FuelDisbursement(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    subProgramme= models.ForeignKey(SubProgramme, on_delete=models.CASCADE,null=True)
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE,null=True)
    driver = models.ForeignKey(UserProfile, on_delete=models.CASCADE,null=True)
    purpose = models.CharField(max_length=1000)
    amount_of_fuel_disbursed = models.DecimalField(max_digits=15, decimal_places=2)
    coupon_serial_number = models.CharField(max_length=50)
    issuer_name = models.CharField(max_length=100)
    transaction_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Fuel disbursement for {self.vehicle.number_plate}"

vehicles/views/maintenance.py
#rest framework
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView

from ..serializers import MaintenanceSerializer,MaintenanceCloseSerializer

from rest_framework import generics
from rest_framework.permissions import IsAuthenticated

from ..models import Maintenance, UserProfile, Vehicle


class MaintenanceList(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        user = request.user

        # Check if the user is a superuser
        if user.is_superuser:
            # Return all maintenance records for superusers
            all_maintenance_records = Maintenance.objects.all().order_by('-created_at')
            serializer = MaintenanceSerializer(all_maintenance_records, many=True)
            return Response(serializer.data)

        # For regular users, check for UserProfile and province
        try:
            user_profile = UserProfile.objects.get(user=user)
        except UserProfile.DoesNotExist:
            return Response({'error': 'UserProfile does not exist for this user.'}, status=404)

        if not user_profile.province:
            return Response({'error': 'No province associated with this user.'}, status=400)

        # Filtering Maintenance records by the user's province
        maintenance_records = Maintenance.objects.filter(vehicle__province=user_profile.province).order_by('-created_at')
        serializer = MaintenanceSerializer(maintenance_records, many=True)
        return Response(serializer.data)
    
class MaintenanceCreate(APIView):
    def post(self, request, *args, **kwargs):
        serializer = MaintenanceSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response({"message": "Maintenance record created successfully"}, status=status.HTTP_201_CREATED)
        # With raise_exception=True, you don't need the below line, but it's here for clarity.
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)   
    
    def handle_exception(self, exc):
        # Check if the exception is a ValidationError with non_field_errors
        if hasattr(exc, 'get_full_details'):
            error_detail = exc.get_full_details()
            if 'non_field_errors' in error_detail:
                # Extract the non-field error message
                custom_error_message = error_detail['non_field_errors'][0]['message']
                # Return a custom response format
                return Response({"Error": custom_error_message}, status=status.HTTP_400_BAD_REQUEST)

        # Fallback to the default exception handling for other types of exceptions
        return super().handle_exception(exc)
     
class MaintenanceDetail(APIView):
    def get(self, request, pk):
        try:
            maintenance = Maintenance.objects.get(id=pk)
            serializer = MaintenanceSerializer(maintenance)
            return Response(serializer.data)
        except Maintenance.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        
class UpdateMaintenance(APIView):
    def get_object(self, pk):
        try:
            return Maintenance.objects.get(id=pk)
        except Maintenance.DoesNotExist:
            raise status.HTTP_404_NOT_FOUND

    def get(self, request, pk):
        return MaintenanceDetail.get(self, request, pk)  # Reuse logic from MaintenanceDetail

    def put(self, request, pk):
        maintenance = self.get_object(pk)
        serializer = MaintenanceSerializer(maintenance, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
""" class MaintenanceClose(APIView):
    def patch(self, request, pk):
        maintenance = Maintenance.objects.get(pk=pk)
        serializer = MaintenanceCloseSerializer(maintenance, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST) """

class MaintenanceClose(APIView):
    def get_object(self, pk):
        try:
            return Maintenance.objects.get(pk=pk)
        except Maintenance.DoesNotExist:
            return Response({'message': 'Maintenance record not found.'}, status=status.HTTP_404_NOT_FOUND)

    def get(self, request, pk):
        maintenance = self.get_object(pk)
        if isinstance(maintenance, Response):  # Check if get_object returned a 404 Response
            return maintenance
        serializer = MaintenanceCloseSerializer(maintenance)
        return Response(serializer.data)

    def put(self, request, pk):
        maintenance = self.get_object(pk)
        if isinstance(maintenance, Response):  # Check if get_object returned a 404 Response
            return maintenance
        
        # Create a mutable copy of the request.data
        data = request.data.copy()
        # Modify the mutable copy
        data['is_serviced'] = True

        serializer = MaintenanceCloseSerializer(maintenance, data=data, partial=True)  # Allow partial update
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class MaintenanceApiList(APIView):
    """
    List all maintenance records for a vehicle that are serviced.
    """
    def get(self, request, vehicle_id):
        # Filter maintenance records by vehicle_id and is_serviced=True
        maintenance = Maintenance.objects.filter(vehicle_id=vehicle_id, is_serviced=True).order_by('-service_date')
        serializer = MaintenanceSerializer(maintenance, many=True)
        return Response(serializer.data)

templates/pages/maintenance/addMaintenance.html
<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="addMaintenanceModal" tabindex="-1" role="dialog" aria-labelledby="addMaintenanceModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addMaintenanceModalLabel">Maintenance</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addMaintenanceForm" autocomplete="off" style="font-size:15px">
                   <div class="row">

                        <div class="mb-3 col-md-6">
                            <div class="form-group">
                                <label for="vehicle">Vehicle</label>
                                <select class="form-control" id="vehicle" name="vehicle" required>
                                    <option value="" selected disabled>Select Vehicle</option>
                                </select>
                            </div>
                        </div>
            
                        <div class="mb-3 col-md-6">
                            <div class="form-group">
                                <label for="last_service_mileage">Last Service Mileage</label>
                                <input type="number" class="form-control"  id="last_service_mileage" name="last_service_mileage" placeholder="Enter Last Service Mileage" required>
                            </div>
                        </div>
                   </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-primary btn-sm" id="submitMaintenanceBtn">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="toastContainer" aria-live="polite" aria-atomic="true" style="position: fixed; top: 16px; right: 16px; z-index: 9999;"></div>
    <!-- Popup -->
    <div class="modal fade" id="numberPlateExistsModal" tabindex="-1" role="dialog" aria-labelledby="numberPlateExistsModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="numberPlateExistsModalLabel">Number Plate Already Exists</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>The number plate you entered already exists. Please enter a different number plate.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>


    

templates/pages/maintenance/addRemark.html
<!-- Modal -->
<div class="modal fade" data-backdrop="static" id="addRemarkModal" tabindex="-1" role="dialog" aria-labelledby="addRemarkModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addRemarkModalLabel">Clear Service</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addRemarkForm" autocomplete="off" style="font-size: 15px">
                    <div class="row">
                      <div class="mb-3 col-md-6">
                        <label for="service_type">Service Type</label>
                        <select class="form-control select2" id="service_type" name="service_type" required>
                          <option selected="selected" disabled="disabled" value="">Select Service Type</option>
                          <option value="A">A</option>
                          <option value="B">B</option>
                          <option value="C">C</option>
                        </select>
                      </div>
                  
                      <div class="mb-3 col-md-6">
                        <div class="form-group">
                          <label for="service_provided">Other Services Provided</label>
                          <input type="text" class="form-control" id="service_provided" name="service_provided" placeholder="Enter Service Provided" required>
                        </div>
                      </div>
                    
                  
                      <div class="mb-3 col-md-6">
                        <label for="service_provider">Service Provider</label>
                        <input type="text" class="form-control" id="service_provider" name="service_provider" placeholder="Enter Service Provider"  required>
                      </div>
                  
                      <div class="mb-3 col-md-12">
                        <label for="remarks " class="form-label">Remarks </label>
                        <textarea name="remarks" id="remarks" class="form-control"  placeholder="Enter remarks for the Vehicle" rows="2"  ></textarea>
                      </div>
                    </div>

                    <div class="modal-footer">
                      <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-outline-primary btn-sm" id="submitMaintenanceBtn">Submit</button>
                    </div>
                  </form>
            </div>
        </div>
    </div>
</div>

<div id="toastContainer" aria-live="polite" aria-atomic="true" style="position: fixed; top: 16px; right: 16px; z-index: 9999;"></div>
    <!-- Popup -->
    <div class="modal fade" id="numberPlateExistsModal" tabindex="-1" role="dialog" aria-labelledby="numberPlateExistsModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="numberPlateExistsModalLabel">Number Plate Already Exists</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>The number plate you entered already exists. Please enter a different number plate.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>


    

templates/pages/maintenance/maintenance.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}| Maintenance {% endblock title %}
{% block extrastyle %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">

{% endblock extrastyle %}
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block content %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Maintenance</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div id="successMessage" class="alert alert-success alert-dismissible fade show" role="alert" style="display: none;">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
        </div>
        
        <div id="errorMessage" class="alert alert-danger alert-dismissible fade show" role="alert" style="display: none;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h1 class="card-title">Maintenance</h1>
                <div class="d-flex justify-content-end">
<!--                   {% if perms.vehicles.add_maintenance %}
                  <a class="btn btn-success btn-sm" href="#" data-toggle="modal" data-target="#addMaintenanceModal"><i class="fas fa-plus-circle"></i> Add Maintenance </a>
                  {% endif %} -->
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="dataTable" class="table table-striped dt-responsive nowrap table-sm" style="font-size:15px">
                  <thead style="background-color: lightblue;">
                    <tr>
                        <th>No.</th>
                        <th>Vehicle</th>
                        <th>Last Service Mileage</th>
                        <th>Before Next Service Mileage</th>
                        <th>Next Service Mileage</th>
         <!--                <th>Status</th> -->
                        {% if perms.vehicles.maintenance_actions  %}
                        <th>Actions</th>
                        {% endif %}
                    </tr>
                  </thead>
                  <tbody>
                    {% for maintenance in maintenance_list %}
                        <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ maintenance.number_plate }}</td>
                        <td>{{ maintenance.last_service_mileage }}</td>
                        <td>{{ maintenance.before_next_service_mileage }}</td>
                        <td>{{ maintenance.next_service_mileage }}</td>
<!--                         <td style="color: {{ maintenance.is_serviced|yesno:'green,red' }}">
                          {{ maintenance.is_serviced|yesno:"Serviced,Running" }}
                        </td> -->
                        {% if perms.vehicles.maintenance_actions  %}
                        <td class="project-actions">
                          {% if perms.vehicles.view_maintenance  %}
                          <a class="btn btn-outline-info btn-sm" href="#" style="padding: 0px 1px; font-size: 13px; color: #060505;">
                            <i class="fas fa-eye"></i> View
                          </a>
                          {% endif %}
                          {% if perms.vehicles.change_maintenance  %}
                          <a class="btn btn-outline-primary btn-sm edit-maintenance-link" href="#" data-toggle="modal" data-target="#editMaintenanceModal" data-maintenance-id="{{ maintenance.id }}" style="padding: 0px 1px; font-size: 13px; color: #010101;">
                            <i class="fas fa-pencil-alt"></i> Edit
                          </a>
                          {% endif %}
                          {% if perms.vehicles.add_maintenance_remark %}
                          <a class="btn btn-outline-info btn-sm" href="#" data-toggle="modal" data-target="#addRemarkModal" data-maintenance-id="{{ maintenance.id }}" style="padding: 0px 1px; font-size: 13px; color: #050505;">
                            <i class="fas fa-edit"></i> Remarks
                          </a>
                          {% endif %}
                        </td>
                        {% endif %}
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
{% include 'pages/maintenance/addMaintenance.html' %}
{% include 'pages/maintenance/editMaintenance.html' %}
{% include 'pages/maintenance/addRemark.html' %}
{% endblock content %}

{% block extra_scripts %}
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- Page specific script -->

{% include 'pages/maintenance/scripts.html' %}

{% endblock extra_scripts %}